name: CI

on:
  push:
    branches:
      - 'master'    
  pull_request:
    branches:
      - 'master'

jobs:
  ci-test:
    name: Unit tests 
    runs-on: ubuntu-latest

    steps:

      - name: Clone and checkout branch
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
            node-version: '16.14.x'

      - name: Install dependencies
        run: npm install

      - name: Running test
        run: npm test

      - name: Running lint
        run: npm run lint:check



